apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    demo: deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      demo: deployment
  template:
    metadata:
      labels:
        demo: deployment
    spec:
      containers:
      - name: app
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  type: NodePort
  selector:
    demo: deployment
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080
