apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: blue
    demo: deployment
spec:
  replicas: 4
  startegy:
      type: Recreate
  selector:
    matchLabels:
      app: blue
      demo: deployment
  template:
    metadata:
      labels:
        app: blue
        demo: deployment
    spec:
      containers:
      - name: blue
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  type: NodePort
  selector:
    app: blue
    demo: deployment
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080
