apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1
  version: 1.27

managedNodeGroups:
  - name: demo
    instanceType: t3.medium
    desiredCapacity: 2
   
